try another delete ver

diff --git a/.github/workflows/create_docker_image.yml b/.github/workflows/create_docker_image.yml
--- a/.github/workflows/create_docker_image.yml
+++ b/.github/workflows/create_docker_image.yml
@@ -120,8 +120,18 @@ jobs:
             ${DOCKER_REPO}:${NXF_VER}-amd64 \
             ${DOCKER_REPO}:${NXF_VER}-arm64 \
             ${DOCKER_REPO}:${NXF_VER}-armv7
-          # Clean up temp tags
-          docker buildx imagetools create -t ${DOCKER_REPO}:${NXF_VER}-amd64 --empty || true
-          docker buildx imagetools create -t ${DOCKER_REPO}:${NXF_VER}-arm64 --empty || true
-          docker buildx imagetools create -t ${DOCKER_REPO}:${NXF_VER}-armv7 --empty || true
-          
+
+      - name: Clean-up temp tags
+      run: |
+        DOCKER_REPO=${{ secrets.DOCKERHUB_USERNAME }}/nxfilter
+        NXF_VER=${{ needs.prep.outputs.NXF_VER }}
+
+        # Clean up temp tags
+        for arch in amd64 arm64 armv7; do
+          echo "Deleting tag ${NXF_VER}-${arch}"
+          curl -X DELETE \
+            -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
+            "https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/nxfilter/tags/${NXF_VER}-${arch}/" \
+            || true
+        done
+            
